-- GUXON 新品專案管理系統 正式 V1
-- 請在 Supabase > SQL Editor 執行一次。
-- 此腳本不會刪除既有 projects / stages / tasks / employees 資料。

-- 1) 補齊專案欄位
alter table public.projects add column if not exists owner_id bigint references public.employees(id) on delete set null;
alter table public.projects add column if not exists budget_version text;
alter table public.projects add column if not exists project_type text;
alter table public.projects add column if not exists success_goal text;

-- 2) 補齊階段欄位
alter table public.stages add column if not exists approval_note text;

-- 3) 補齊任務欄位
alter table public.tasks add column if not exists due_offset integer;
alter table public.tasks add column if not exists due_date date;
alter table public.tasks add column if not exists note text;
alter table public.tasks add column if not exists sort_order integer not null default 0;
alter table public.tasks add column if not exists updated_at timestamptz not null default now();

-- 相容既有系統：完成狀態統一使用「已完成」
-- 若先前正式 V1 SQL 曾把「已完成」改成「完成」，此處會安全還原。
update public.tasks set status = '已完成' where status = '完成';

-- 4) 每階段通關檢核
create table if not exists public.stage_gates (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  project_id bigint not null references public.projects(id) on delete cascade,
  stage_id bigint not null references public.stages(id) on delete cascade,
  label text not null,
  checked boolean not null default false,
  sort_order integer not null default 0
);

create index if not exists idx_stages_project_id on public.stages(project_id);
create index if not exists idx_tasks_project_id on public.tasks(project_id);
create index if not exists idx_tasks_stage_id on public.tasks(stage_id);
create index if not exists idx_tasks_assignee_id on public.tasks(assignee_id);
create index if not exists idx_tasks_due_date on public.tasks(due_date);
create index if not exists idx_stage_gates_project_id on public.stage_gates(project_id);
create index if not exists idx_stage_gates_stage_id on public.stage_gates(stage_id);

-- 5) RLS（目前模式：內部測試 / 尚未強制登入）
alter table public.projects enable row level security;
alter table public.stages enable row level security;
alter table public.tasks enable row level security;
alter table public.employees enable row level security;
alter table public.stage_gates enable row level security;

-- 使用固定 policy 名稱，重跑本腳本也安全
drop policy if exists "guxon_v1_projects" on public.projects;
drop policy if exists "guxon_v1_stages" on public.stages;
drop policy if exists "guxon_v1_tasks" on public.tasks;
drop policy if exists "guxon_v1_employees" on public.employees;
drop policy if exists "guxon_v1_gates" on public.stage_gates;

create policy "guxon_v1_projects" on public.projects for all to anon, authenticated using (true) with check (true);
create policy "guxon_v1_stages" on public.stages for all to anon, authenticated using (true) with check (true);
create policy "guxon_v1_tasks" on public.tasks for all to anon, authenticated using (true) with check (true);
create policy "guxon_v1_employees" on public.employees for all to anon, authenticated using (true) with check (true);
create policy "guxon_v1_gates" on public.stage_gates for all to anon, authenticated using (true) with check (true);

-- 6) Realtime：多人同時操作時自動更新
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='projects') THEN ALTER PUBLICATION supabase_realtime ADD TABLE public.projects; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='stages') THEN ALTER PUBLICATION supabase_realtime ADD TABLE public.stages; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='tasks') THEN ALTER PUBLICATION supabase_realtime ADD TABLE public.tasks; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='employees') THEN ALTER PUBLICATION supabase_realtime ADD TABLE public.employees; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='stage_gates') THEN ALTER PUBLICATION supabase_realtime ADD TABLE public.stage_gates; END IF;
END $$;
