-- GUXON 新品管理平台｜新品執行管理模組
-- 在 Supabase > SQL Editor 執行一次。
-- 不會刪除既有 projects / stages / tasks / stage_gates / employees 資料。

create table if not exists public.execution_sections (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  project_id bigint not null references public.projects(id) on delete cascade,
  section_number integer not null,
  name text not null,
  description text,
  sort_order integer not null default 0
);

create table if not exists public.execution_tasks (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  project_id bigint not null references public.projects(id) on delete cascade,
  section_id bigint not null references public.execution_sections(id) on delete cascade,
  title text not null,
  description text,
  assignee_id bigint references public.employees(id) on delete set null,
  reviewer_id bigint references public.employees(id) on delete set null,
  status text not null default '未開始',
  priority text not null default '中',
  start_date date,
  due_date date,
  start_offset integer,
  due_offset integer,
  depends_on_task_id bigint references public.execution_tasks(id) on delete set null,
  note text,
  sort_order integer not null default 0
);

create index if not exists idx_execution_sections_project_id on public.execution_sections(project_id);
create index if not exists idx_execution_tasks_project_id on public.execution_tasks(project_id);
create index if not exists idx_execution_tasks_section_id on public.execution_tasks(section_id);
create index if not exists idx_execution_tasks_assignee_id on public.execution_tasks(assignee_id);
create index if not exists idx_execution_tasks_reviewer_id on public.execution_tasks(reviewer_id);
create index if not exists idx_execution_tasks_due_date on public.execution_tasks(due_date);
create index if not exists idx_execution_tasks_dependency on public.execution_tasks(depends_on_task_id);

alter table public.execution_sections enable row level security;
alter table public.execution_tasks enable row level security;

drop policy if exists "guxon_execution_sections" on public.execution_sections;
drop policy if exists "guxon_execution_tasks" on public.execution_tasks;
create policy "guxon_execution_sections" on public.execution_sections for all to anon, authenticated using (true) with check (true);
create policy "guxon_execution_tasks" on public.execution_tasks for all to anon, authenticated using (true) with check (true);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='execution_sections') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.execution_sections;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='execution_tasks') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.execution_tasks;
  END IF;
END $$;
