-- 可編輯「新品執行模板」資料結構
-- 執行後，模板的區塊與任務可由後台自由新增、改名、排序、停用與刪除。

create table if not exists public.execution_template_sections (
  id bigint generated by default as identity primary key,
  project_kind text not null default 'brand' check (project_kind in ('brand','1688')),
  name text not null,
  description text,
  sort_order integer not null default 0,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.execution_template_tasks (
  id bigint generated by default as identity primary key,
  section_id bigint not null references public.execution_template_sections(id) on delete cascade,
  title text not null,
  description text,
  department text,
  reviewer_department text,
  default_assignee_id bigint references public.employees(id) on delete set null,
  default_reviewer_id bigint references public.employees(id) on delete set null,
  default_priority text not null default '中',
  default_start_offset integer not null default -30,
  default_due_offset integer not null default -21,
  dependency_task_id bigint references public.execution_template_tasks(id) on delete set null,
  sort_order integer not null default 0,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_execution_template_sections_kind_sort
  on public.execution_template_sections(project_kind, sort_order);
create index if not exists idx_execution_template_tasks_section_sort
  on public.execution_template_tasks(section_id, sort_order);

-- 目前此系統是內部管理工具；沿用既有 Supabase anon/authenticated 存取方式。
alter table public.execution_template_sections enable row level security;
alter table public.execution_template_tasks enable row level security;

drop policy if exists "execution_template_sections_select" on public.execution_template_sections;
drop policy if exists "execution_template_sections_write" on public.execution_template_sections;
drop policy if exists "execution_template_tasks_select" on public.execution_template_tasks;
drop policy if exists "execution_template_tasks_write" on public.execution_template_tasks;

create policy "execution_template_sections_select" on public.execution_template_sections
for select using (true);
create policy "execution_template_sections_write" on public.execution_template_sections
for all using (true) with check (true);
create policy "execution_template_tasks_select" on public.execution_template_tasks
for select using (true);
create policy "execution_template_tasks_write" on public.execution_template_tasks
for all using (true) with check (true);

notify pgrst, 'reload schema';
