-- GUXON AI 新品策略工作區 v1
-- 目的：策略決策與員工執行任務分流，兩條線可平行進行。
-- 本檔只新增資料表，不修改既有 projects / stages / tasks / execution_* 資料。

create table if not exists public.strategy_sections (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  section_key text not null,
  name text not null,
  description text,
  sort_order integer not null default 0,
  status text not null default '未開始' check (status in ('未開始','進行中','待確認','已確認')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(project_id, section_key)
);

create table if not exists public.strategy_items (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  section_id bigint not null references public.strategy_sections(id) on delete cascade,
  item_key text,
  title text not null,
  content text,
  source_status text not null default '缺少資料' check (source_status in ('缺少資料','AI建議','待確認','已確認')),
  source_note text,
  assignee_id bigint references public.employees(id) on delete set null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.strategy_dependencies (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  strategy_item_id bigint not null references public.strategy_items(id) on delete cascade,
  execution_task_id bigint not null references public.execution_tasks(id) on delete cascade,
  dependency_type text not null default '提醒' check (dependency_type in ('提醒','定稿前確認','開始前確認')),
  note text,
  created_at timestamptz not null default now(),
  unique(strategy_item_id, execution_task_id)
);

create table if not exists public.strategy_reports (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  version text not null default 'v1.0',
  status text not null default '草稿' check (status in ('草稿','待審','已核准')),
  title text,
  summary text,
  file_url text,
  generated_at timestamptz,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_strategy_sections_project on public.strategy_sections(project_id, sort_order);
create index if not exists idx_strategy_items_section on public.strategy_items(section_id, sort_order);
create index if not exists idx_strategy_items_project on public.strategy_items(project_id);
create index if not exists idx_strategy_dependencies_project on public.strategy_dependencies(project_id);
create index if not exists idx_strategy_reports_project on public.strategy_reports(project_id, created_at desc);

-- 新專案策略工作區的 6 大區塊，前端建立專案時使用：
-- 1 市場與競品
-- 2 商品定位與受眾
-- 3 賣點與使用情境
-- 4 商業策略
-- 5 上市與行銷策略
-- 6 上市前決策
--
-- source_status 用途：
-- 缺少資料：尚未有足夠資訊
-- AI建議：由 AI 產生，尚未人工確認
-- 待確認：需要人員／供應商／數據佐證
-- 已確認：可作為正式策略與對外內容依據
--
-- strategy_dependencies 不會阻止執行任務進行；由 dependency_type 決定提醒強度：
-- 提醒：執行可繼續，只顯示關聯提醒
-- 定稿前確認：工作可先做，但最終定稿前需確認策略
-- 開始前確認：該工作原則上應等待指定策略確認
