-- AI 新品策略資料中心
-- 每個新品只維護一份核心上下文，所有 AI 策略項目共用。

create table if not exists public.strategy_contexts (
  id bigint generated by default as identity primary key,
  project_id bigint not null unique references public.projects(id) on delete cascade,
  product_basics text,
  specs_features text,
  cost_pricing text,
  target_audience text,
  sales_channels text,
  competitors text,
  supplier_testing text,
  background_notes text,
  confirmation_status jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists strategy_contexts_project_id_idx on public.strategy_contexts(project_id);

alter table public.strategy_contexts enable row level security;

drop policy if exists "strategy_contexts_select" on public.strategy_contexts;
drop policy if exists "strategy_contexts_write" on public.strategy_contexts;

create policy "strategy_contexts_select" on public.strategy_contexts
for select using (true);

create policy "strategy_contexts_write" on public.strategy_contexts
for all using (true) with check (true);

notify pgrst, 'reload schema';
