from pathlib import Path
p=Path('app/page.tsx')
s=p.read_text()
old="""      const strategyForProject=strategyItems.filter(x=>x.project_id===p.id)\n      const strategyReady=is1688 || strategyForProject.length===0 || strategyForProject.every(x=>x.source_status==='已確認')\n      if(list.length>0 && list.every(t=>isDone(t.status)) && productReady && strategyReady) updateProject(p.id,{status:'已結案'})"""
new="""      const strategyForProject=strategyItems.filter(x=>x.project_id===p.id)\n      const strategyReady=is1688 || (!!(p as any).strategy_completed && strategyForProject.length>0 && strategyForProject.every(x=>x.source_status==='已確認'))\n      if(list.length>0 && list.every(t=>isDone(t.status)) && productReady && strategyReady) updateProject(p.id,{status:'已結案'})"""
assert old in s
s=s.replace(old,new)
old="""      return <button key={p.id} className={`project-card ${is1688?'project-card-1688':''} ${overdueFlag?'project-card-overdue':''}`} onClick={()=>{openProject(p.id);const first=stages.find(s=>s.project_id===p.id)?.id;if(first)setExpanded({[first]:true})}}><div className=\"project-top\"><div><div className=\"project-heading-line\"><h2>{p.name}</h2><span className={`kind-badge ${is1688?'kind-1688':'kind-brand'}`}>{is1688?'1688 新品':'品牌新品'}</span>{overdueFlag&&<span className=\"pill pill-danger\">已逾期</span>}</div><p>{p.version||'-'} ・ 負責：{owner}</p></div><StatusPill text={p.status||'未設定'}/></div><div className=\"project-meta\"><span>上市日 <b>{p.launch_date||'-'}</b></span><span>正式價 <b>NT$ {p.retail_price??'-'}</b></span><span>團購價 <b>NT$ {p.group_price??'-'}</b></span><span>{is1688?'簡易工作':'執行工作'} <b>{is1688?`${pt.filter(t=>isDone(t.status)).length}/${pt.length}`:`${et.filter(t=>isDone(t.status)).length}/${et.filter(t=>countsInExecutionProgress(t.status)).length}`}</b></span></div>{is1688?<div className=\"single-progress\"><span>1688 上架進度 <b>{pct}%</b></span><div className=\"progress\"><i style={{width:`${pct}%`}}/></div></div>:<div className=\"dual-progress\"><div><span>策略管理 <b>{pct}%</b></span><div className=\"progress\"><i style={{width:`${pct}%`}}/></div></div><div><span>執行管理 <b>{et.length?`${ep}%`:'尚未建立'}</b></span><div className=\"progress execution-progress\"><i style={{width:`${ep}%`}}/></div></div></div>}</button>"""
new="""      const strategyProgress=strategyDecisionProgress(p.id)\n      const strategyComplete=!!(p as any).strategy_completed\n      return <button key={p.id} className={`project-card ${is1688?'project-card-1688':''} ${overdueFlag?'project-card-overdue':''}`} onClick={()=>{openProject(p.id);const first=stages.find(s=>s.project_id===p.id)?.id;if(first)setExpanded({[first]:true})}}><div className=\"project-top\"><div><div className=\"project-heading-line\"><h2>{p.name}</h2><span className={`kind-badge ${is1688?'kind-1688':'kind-brand'}`}>{is1688?'1688 新品':'品牌新品'}</span>{overdueFlag&&<span className=\"pill pill-danger\">已逾期</span>}</div><p>{p.version||'-'} ・ 負責：{owner}</p></div><StatusPill text={p.status||'未設定'}/></div><div className=\"project-meta\"><span>上市日 <b>{p.launch_date||'-'}</b></span><span>正式價 <b>NT$ {p.retail_price??'-'}</b></span><span>團購價 <b>NT$ {p.group_price??'-'}</b></span><span>{is1688?'簡易工作':'執行工作'} <b>{is1688?`${pt.filter(t=>isDone(t.status)).length}/${pt.length}`:`${et.filter(t=>isDone(t.status)).length}/${et.filter(t=>countsInExecutionProgress(t.status)).length}`}</b></span></div>{is1688?<div className=\"single-progress\"><span>1688 上架進度 <b>{pct}%</b></span><div className=\"progress\"><i style={{width:`${pct}%`}}/></div></div>:<div className=\"dual-progress\"><div><span>策略管理 <b>{strategyComplete?'✓ 已完成':`${strategyProgress.done}/${strategyProgress.total} 已確認`}</b></span><div className=\"progress\"><i style={{width:`${strategyComplete?100:(strategyProgress.total?Math.round(strategyProgress.done/strategyProgress.total*100):0)}%`}}/></div></div><div><span>執行管理 <b>{et.length?`${ep}%`:'尚未建立'}</b></span><div className=\"progress execution-progress\"><i style={{width:`${ep}%`}}/></div></div></div>}</button>"""
assert old in s
s=s.replace(old,new)
old="""function StrategyProjectView(props:ProjectViewProps & {onOpenExecution:()=>void}) {\n  const {project}=props\n  return <main className=\"page\"><div className=\"shell\"><Header/>"""
new="""function StrategyProjectView(props:ProjectViewProps & {onOpenExecution:()=>void}) {\n  const {project}=props\n  const strategyCompleted=!!(project as any).strategy_completed\n  const setStrategyCompleted=(checked:boolean)=>props.onUpdateProject(project.id,{strategy_completed:checked,strategy_completed_at:checked?new Date().toISOString():null} as any)\n  return <main className=\"page\"><div className=\"shell\"><Header/>"""
assert old in s
s=s.replace(old,new)
old="""    <section className=\"overall\"><div><b>新品策略管理</b><p>這裡只管理策略決策，不再建立第二套執行任務。</p></div><strong style={{fontSize:18}}>決策工作區</strong></section>"""
new="""    <section className=\"overall\"><div><b>新品策略管理</b><p>這裡只管理策略決策，不再建立第二套執行任務。</p></div><div style={{display:'flex',alignItems:'center',gap:12}}><span style={{fontSize:14,color:'#6b7280'}}>完成期限 {(project as any).strategy_due_date||'未設定'}</span><label className={`strategy-complete-toggle ${strategyCompleted?'is-complete':''}`}><input type=\"checkbox\" checked={strategyCompleted} onChange={e=>setStrategyCompleted(e.target.checked)}/><b>{strategyCompleted?'策略已完成':'勾選整體策略已完成'}</b></label></div></section>\n    {strategyCompleted&&<div className=\"alert ok\"><b>✓ 此商品策略已完成</b><p>{(project as any).strategy_completed_at?`完成時間：${new Date((project as any).strategy_completed_at).toLocaleString('zh-TW')}`:'已完成策略確認。'}</p></div>}"""
assert old in s
s=s.replace(old,new)
p.write_text(s)
