from pathlib import Path
p=Path('app/page.tsx')
s=p.read_text()
s=s.replace("  const [strategyItems, setStrategyItems] = useState<any[]>([])\n", "  const [strategyItems, setStrategyItems] = useState<any[]>([])\n  const [performanceResetAt,setPerformanceResetAt]=useState<string|null>(null)\n")
s=s.replace("    const [p,s,t,g,e,xs,xt,xd,ps,si] = await Promise.all([", "    const [p,s,t,g,e,xs,xt,xd,ps,si,settings] = await Promise.all([")
s=s.replace("      supabase.from('strategy_items').select('project_id,source_status'),\n    ])", "      supabase.from('strategy_items').select('project_id,source_status'),\n      supabase.from('app_settings').select('key,value').eq('key','performance_reset').maybeSingle(),\n    ])")
s=s.replace("    if (!si.error) setStrategyItems(si.data||[])\n", "    if (!si.error) setStrategyItems(si.data||[])\n    if (!settings.error) setPerformanceResetAt((settings.data?.value as any)?.reset_at||null)\n")
old="""  const employeePerformance=employees.filter(e=>e.active).map(e=>{\n    const assigned=executionTasks.filter(t=>t.assignee_id===e.id&&t.status!=='不適用')\n    const currentOverdue=assigned.filter(t=>t.due_date&&t.due_date<todayIso()&&!isDone(t.status))\n    const overdueDays=currentOverdue.reduce((sum,t)=>sum+Math.max(0,-daysFromToday(t.due_date!)),0)\n    const done=assigned.filter(t=>isDone(t.status))\n    const onTime=done.filter(t=>!t.due_date || (t.updated_at||'').slice(0,10)<=t.due_date).length\n    return {employee:e,assigned:assigned.length,done:done.length,currentOverdue:currentOverdue.length,overdueDays,onTimeRate:done.length?Math.round(onTime/done.length*100):0}\n  })\n"""
new="""  const resetDate=performanceResetAt?.slice(0,10)||null\n  const employeePerformance=employees.filter(e=>e.active).map(e=>{\n    const assigned=executionTasks.filter(t=>t.assignee_id===e.id&&t.status!=='不適用')\n    const currentOverdue=assigned.filter(t=>t.due_date&&t.due_date<todayIso()&&!isDone(t.status))\n    const overdueDays=currentOverdue.reduce((sum,t)=>{\n      const start=resetDate && resetDate>t.due_date! ? resetDate : t.due_date!\n      return sum+Math.max(0,-daysFromToday(start))\n    },0)\n    const done=assigned.filter(t=>isDone(t.status))\n    const periodDone=done.filter(t=>!resetDate || (t.updated_at||'').slice(0,10)>=resetDate)\n    const onTime=periodDone.filter(t=>!t.due_date || (t.updated_at||'').slice(0,10)<=t.due_date).length\n    const lateDone=periodDone.filter(t=>t.due_date && (t.updated_at||'').slice(0,10)>t.due_date)\n    const historicalOverdueDays=lateDone.reduce((sum,t)=>{\n      const completed=(t.updated_at||'').slice(0,10)\n      const start=resetDate && resetDate>t.due_date! ? resetDate : t.due_date!\n      if(!completed||completed<=start) return sum\n      return sum+Math.max(0,Math.round((new Date(completed+'T00:00:00').getTime()-new Date(start+'T00:00:00').getTime())/86400000))\n    },0)\n    return {employee:e,assigned:assigned.length,done:done.length,currentOverdue:currentOverdue.length,overdueDays,periodDone:periodDone.length,lateDone:lateDone.length,historicalOverdueDays,onTimeRate:periodDone.length?Math.round(onTime/periodDone.length*100):0}\n  })\n  const isBoss=!REQUIRE_AUTH || currentEmployee?.role==='admin'\n  async function resetPerformanceOverdue() {\n    if(!isBoss) return\n    if(!window.confirm('確定要重置逾期績效起算日嗎？重置後，先前累積的逾期天數不再列入績效統計。')) return\n    const now=new Date().toISOString()\n    const {error}=await supabase.from('app_settings').upsert({key:'performance_reset',value:{reset_at:now},updated_at:now,updated_by:currentEmployee?.id||null},{onConflict:'key'})\n    if(error) return alert('重置失敗：'+error.message)\n    setPerformanceResetAt(now)\n    alert('逾期績效已重置，從今天重新計算。')\n  }\n"""
if old not in s: raise SystemExit('performance block not found')
s=s.replace(old,new)
old_ui="""<div className=\"panel\"><div className=\"panel-head\"><b>團隊工作狀況</b><small>目前執行狀況，供管理與績效參考</small></div><div className=\"team-performance\">{employeePerformance.map(x=><div className=\"performance-row\" key={x.employee.id}><div className=\"performance-person\"><b>{x.employee.name}</b><small>{x.employee.department||'未設定職務'}</small></div><div className=\"performance-metric\"><small>完成任務</small><b>{x.done}/{x.assigned}</b></div><div className=\"performance-metric\"><small>準時率</small><b>{x.onTimeRate}%</b></div><div className=\"performance-metric\"><small>逾期任務</small><b className={x.currentOverdue>0?'danger-text':''}>{x.currentOverdue}</b></div><div className=\"performance-metric\"><small>目前逾期總天數</small><b className={x.overdueDays>0?'danger-text':''}>{x.overdueDays} 天</b></div></div>)}</div><p className=\"performance-note\">逾期天數僅計算目前尚未完成且已超過期限的執行任務；完成後不再累加於此數字。</p></div>"""
new_ui="""<div className=\"panel\"><div className=\"panel-head\"><div><b>團隊工作狀況</b><small>目前工作狀況＋重置後歷史績效</small></div>{isBoss&&<button className=\"btn\" onClick={resetPerformanceOverdue}>重置逾期天數</button>}</div>{resetDate&&<p className=\"performance-note\">績效起算日：{resetDate}</p>}<div className=\"team-performance\">{employeePerformance.map(x=><div className=\"performance-row\" key={x.employee.id}><div className=\"performance-person\"><b>{x.employee.name}</b><small>{x.employee.department||'未設定職務'}</small></div><div className=\"performance-metric\"><small>目前逾期</small><b className={x.currentOverdue>0?'danger-text':''}>{x.currentOverdue} 件／{x.overdueDays} 天</b></div><div className=\"performance-metric\"><small>期間完成</small><b>{x.periodDone} 件</b></div><div className=\"performance-metric\"><small>逾期完成</small><b className={x.lateDone>0?'danger-text':''}>{x.lateDone} 件／{x.historicalOverdueDays} 天</b></div><div className=\"performance-metric\"><small>準時率</small><b>{x.onTimeRate}%</b></div></div>)}</div><p className=\"performance-note\">目前逾期＝尚未完成的執行任務；歷史績效＝起算日後完成的執行任務。策略決策不列入員工逾期績效。</p></div>"""
if old_ui not in s: raise SystemExit('performance ui not found')
s=s.replace(old_ui,new_ui)
p.write_text(s)
