from pathlib import Path
p=Path('app/strategy/[projectId]/page.tsx')
s=p.read_text()
s=s.replace("import { useEffect,useMemo,useState } from 'react'", "import { useEffect,useMemo,useState } from 'react'")
anchor="const emptyContext=():StrategyContext=>({product_basics:'',specs_features:'',cost_pricing:'',target_audience:'',sales_channels:'',competitors:'',supplier_testing:'',background_notes:'',confirmation_status:{}})"
insert="""
const PUBLIC_SPEC_FIELDS=[
 ['product_name','產品名稱'],['model','型號'],['version','版本'],['category','產品類別'],['colors','顏色'],['dimensions','尺寸'],['weight','重量'],['materials','材質'],['battery','電池／容量'],['input_output','輸入／輸出'],['features','主要功能'],['compatibility','相容性'],['accessories','包裝配件'],['certifications','認證／安規'],['warranty','保固'],['launch_date','上市日期'],['public_notes','其他公開規格']
] as const
const INTERNAL_FIELDS=[
 ['cost','採購成本'],['retail_price','建議售價'],['promo_price','活動／團購價'],['margin','毛利條件'],['target_audience','目標客群'],['core_positioning','核心定位／差異化'],['competitors','主要競品與價格帶'],['sales_channels','預計銷售通路'],['supplier','供應商資訊'],['testing','樣品／實測資料'],['market_notes','市場機會／風險'],['internal_notes','其他內部備註']
] as const
type SheetData=Record<string,string>
"""
if 'PUBLIC_SPEC_FIELDS' not in s:s=s.replace(anchor,anchor+'\n'+insert)
s=s.replace("const [context,setContext]=useState<StrategyContext>(emptyContext()),[contextOpen,setContextOpen]=useState(true),[contextSaving,setContextSaving]=useState(false)","const [context,setContext]=useState<StrategyContext>(emptyContext()),[contextOpen,setContextOpen]=useState(true),[contextSaving,setContextSaving]=useState(false)\n const [sheet,setSheet]=useState<{public_specs:SheetData;internal_analysis:SheetData;confirmation_status:Record<string,boolean>;completed:boolean}>({public_specs:{},internal_analysis:{},confirmation_status:{},completed:false}),[sheetOpen,setSheetOpen]=useState(true),[sheetSaving,setSheetSaving]=useState(false)")
s=s.replace("const[p,s,i,c]=await Promise.all([supabase.from('projects').select('*').eq('id',projectId).maybeSingle(),supabase.from('strategy_sections').select('*').eq('project_id',projectId).order('sort_order'),supabase.from('strategy_items').select('*').eq('project_id',projectId).order('sort_order'),supabase.from('strategy_contexts').select('*').eq('project_id',projectId).maybeSingle()])", "const[p,s,i,c,ps]=await Promise.all([supabase.from('projects').select('*').eq('id',projectId).maybeSingle(),supabase.from('strategy_sections').select('*').eq('project_id',projectId).order('sort_order'),supabase.from('strategy_items').select('*').eq('project_id',projectId).order('sort_order'),supabase.from('strategy_contexts').select('*').eq('project_id',projectId).maybeSingle(),supabase.from('product_data_sheets').select('*').eq('project_id',projectId).maybeSingle()])")
s=s.replace("if(!c.error&&c.data){const x:any=c.data;setContext({...emptyContext(),...x,confirmation_status:x.confirmation_status||{}})}setLoading(false)","if(!c.error&&c.data){const x:any=c.data;setContext({...emptyContext(),...x,confirmation_status:x.confirmation_status||{}})}if(!ps.error&&ps.data){const x:any=ps.data;setSheet({public_specs:x.public_specs||{},internal_analysis:x.internal_analysis||{},confirmation_status:x.confirmation_status||{},completed:!!x.completed})}setLoading(false)")
needle="async function createWorkspace()"
func="""async function saveSheet(){setSheetSaving(true);const row:any={project_id:projectId,public_specs:sheet.public_specs,internal_analysis:sheet.internal_analysis,confirmation_status:sheet.confirmation_status,completed:sheet.completed,completed_at:sheet.completed?new Date().toISOString():null,updated_at:new Date().toISOString()};const{error}=await supabase.from('product_data_sheets').upsert(row,{onConflict:'project_id'});setSheetSaving(false);if(error)return alert('儲存產品資料表失敗：'+error.message);const publicText=PUBLIC_SPEC_FIELDS.map(([k,l])=>sheet.public_specs[k]?`${l}：${sheet.public_specs[k]}`:'').filter(Boolean).join('\\n');const internalText=INTERNAL_FIELDS.map(([k,l])=>sheet.internal_analysis[k]?`${l}：${sheet.internal_analysis[k]}`:'').filter(Boolean).join('\\n');setContext(c=>({...c,product_basics:publicText||c.product_basics,specs_features:publicText||c.specs_features,cost_pricing:internalText||c.cost_pricing,target_audience:sheet.internal_analysis.target_audience||c.target_audience,sales_channels:sheet.internal_analysis.sales_channels||c.sales_channels,competitors:sheet.internal_analysis.competitors||c.competitors,supplier_testing:[sheet.internal_analysis.supplier,sheet.internal_analysis.testing].filter(Boolean).join('\\n')||c.supplier_testing}))}
 function exportPublicSpecs(){const rows=[['欄位','內容'],...PUBLIC_SPEC_FIELDS.map(([k,l])=>[l,sheet.public_specs[k]||''])];const csv='\\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\\r\\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`${project?.name||'新品'}_客服基本規格.csv`;a.click();URL.revokeObjectURL(a.href)}
 """
if 'async function saveSheet()' not in s:s=s.replace(needle,func+needle)
marker="<section style={styles.contextCard}><button style={styles.contextHead}"
block="""<section style={styles.contextCard}><button style={styles.contextHead} onClick={()=>setSheetOpen(x=>!x)}><div><small style={styles.eyebrow}>PRODUCT DATA SHEET</small><h2 style={{margin:'4px 0'}}>新品產品資料表</h2><p style={{...styles.muted,margin:0}}>先維護產品規格，再由策略區塊引用。公開規格可匯出給 AI 客服；成本、市場與供應商等內部資料不會包含在客服匯出檔。</p></div><div style={{textAlign:'right'}}><b>{sheet.completed?'已完成':'待完成'}</b><div style={styles.muted}>{sheetOpen?'收起':'展開'}</div></div></button>{sheetOpen&&<div style={styles.contextBody}><h3>公開產品規格</h3><div style={styles.contextGrid}>{PUBLIC_SPEC_FIELDS.map(([key,label])=><div key={key} style={styles.contextItem}><div style={styles.contextLabel}><b>{label}</b></div><textarea style={styles.contextTextarea} value={sheet.public_specs[key]||''} onChange={e=>setSheet(x=>({...x,public_specs:{...x.public_specs,[key]:e.target.value}}))}/></div>)}</div><h3 style={{marginTop:22}}>內部市場／商業資料 <small style={styles.muted}>（不匯出至客服規格）</small></h3><div style={styles.contextGrid}>{INTERNAL_FIELDS.map(([key,label])=><div key={key} style={styles.contextItem}><div style={styles.contextLabel}><b>{label}</b></div><textarea style={styles.contextTextarea} value={sheet.internal_analysis[key]||''} onChange={e=>setSheet(x=>({...x,internal_analysis:{...x.internal_analysis,[key]:e.target.value}}))}/></div>)}</div><div style={styles.saveRow}><label style={styles.check}><input type="checkbox" checked={sheet.completed} onChange={e=>setSheet(x=>({...x,completed:e.target.checked}))}/>產品資料表已完成</label><div style={{display:'flex',gap:8}}><button style={styles.aiButton} onClick={exportPublicSpecs}>匯出客服基本規格 CSV</button><button style={styles.primary} disabled={sheetSaving} onClick={saveSheet}>{sheetSaving?'儲存中…':'儲存產品資料表'}</button></div></div></div>}</section>\n  """
if 'PRODUCT DATA SHEET' not in s:s=s.replace(marker,block+marker)
p.write_text(s)
