from pathlib import Path
p=Path('app/strategy/[projectId]/page.tsx')
s=p.read_text()
old="""async function saveSheet(){setSheetSaving(true);const{error}=await supabase.from('product_data_sheets').upsert({project_id:projectId,public_specs:sheet.public_specs,internal_analysis:sheet.internal_analysis,completed:sheet.completed,completed_at:sheet.completed?new Date().toISOString():null,updated_at:new Date().toISOString()},{onConflict:'project_id'});setSheetSaving(false);if(error)return alert('儲存產品資料表失敗：'+error.message);const pub=PUBLIC_FIELDS.map(([k,l])=>sheet.public_specs[k]?`${l}：${sheet.public_specs[k]}`:'').filter(Boolean).join('\\n');const internal=INTERNAL_FIELDS.map(([k,l])=>sheet.internal_analysis[k]?`${l}：${sheet.internal_analysis[k]}`:'').filter(Boolean).join('\\n');setContext(c=>({...c,product_basics:pub,specs_features:pub,cost_pricing:internal,target_audience:sheet.internal_analysis.target_audience||c.target_audience,sales_channels:sheet.internal_analysis.sales_channels||c.sales_channels,competitors:sheet.internal_analysis.competitors||c.competitors,supplier_testing:[sheet.internal_analysis.supplier,sheet.internal_analysis.testing].filter(Boolean).join('\\n')}))}"""
new="""async function saveSheet(){setSheetSaving(true);const now=new Date().toISOString();const{error}=await supabase.from('product_data_sheets').upsert({project_id:projectId,public_specs:sheet.public_specs,internal_analysis:sheet.internal_analysis,completed:sheet.completed,completed_at:sheet.completed?now:null,updated_at:now},{onConflict:'project_id'});if(error){setSheetSaving(false);return alert('儲存產品資料表失敗：'+error.message)}const pub=PUBLIC_FIELDS.map(([k,l])=>sheet.public_specs[k]?`${l}：${sheet.public_specs[k]}`:'').filter(Boolean).join('\\n');const internal=INTERNAL_FIELDS.map(([k,l])=>sheet.internal_analysis[k]?`${l}：${sheet.internal_analysis[k]}`:'').filter(Boolean).join('\\n');const nextContext={...context,product_basics:pub,specs_features:pub,cost_pricing:internal,target_audience:sheet.internal_analysis.target_audience||context.target_audience,sales_channels:sheet.internal_analysis.sales_channels||context.sales_channels,competitors:sheet.internal_analysis.competitors||context.competitors,supplier_testing:[sheet.internal_analysis.supplier,sheet.internal_analysis.testing].filter(Boolean).join('\\n')};setContext(nextContext);const{error:contextError}=await supabase.from('strategy_contexts').upsert({project_id:projectId,...nextContext,updated_at:now},{onConflict:'project_id'});setSheetSaving(false);if(contextError)return alert('產品資料已儲存，但同步 AI 策略資料失敗：'+contextError.message)}"""
assert old in s, 'saveSheet block not found'
s=s.replace(old,new)
old2="""<button style={styles.back} onClick={()=>router.push('/')}>← 返回新品管理平台</button>"""
new2="""<button style={styles.back} onClick={()=>{if(window.history.length>1)router.back();else router.push('/')}}>← 返回上一頁</button>"""
assert old2 in s, 'back button not found'
s=s.replace(old2,new2)
p.write_text(s)
