from pathlib import Path

page=Path('app/page.tsx')
s=page.read_text()
old="""    return {employee:e,currentOverdue:currentOverdue.length,overdueDays,onTimeRate:done.length?Math.round(onTime/done.length*100):0}\n  })"""
new="""    return {employee:e,assigned:assigned.length,done:done.length,currentOverdue:currentOverdue.length,overdueDays,onTimeRate:done.length?Math.round(onTime/done.length*100):0}\n  })"""
assert old in s
s=s.replace(old,new)
old="""<div className=\"panel\"><div className=\"panel-head\"><b>團隊工作狀況</b><small>逾期天數供管理與績效參考</small></div><div className=\"team-performance\">{employeePerformance.map(x=><div className=\"performance-row\" key={x.employee.id}><b>{x.employee.name}</b><span>準時率 {x.onTimeRate}%</span><span>目前逾期 {x.currentOverdue}</span><span className={x.overdueDays>0?'danger-text':''}>累計逾期 {x.overdueDays} 天</span></div>)}</div></div>"""
new="""<div className=\"panel\"><div className=\"panel-head\"><b>團隊工作狀況</b><small>目前執行狀況，供管理與績效參考</small></div><div className=\"team-performance\">{employeePerformance.map(x=><div className=\"performance-row\" key={x.employee.id}><div className=\"performance-person\"><b>{x.employee.name}</b><small>{x.employee.department||'未設定職務'}</small></div><div className=\"performance-metric\"><small>完成任務</small><b>{x.done}/{x.assigned}</b></div><div className=\"performance-metric\"><small>準時率</small><b>{x.onTimeRate}%</b></div><div className=\"performance-metric\"><small>逾期任務</small><b className={x.currentOverdue>0?'danger-text':''}>{x.currentOverdue}</b></div><div className=\"performance-metric\"><small>目前逾期總天數</small><b className={x.overdueDays>0?'danger-text':''}>{x.overdueDays} 天</b></div></div>)}</div><p className=\"performance-note\">逾期天數僅計算目前尚未完成且已超過期限的執行任務；完成後不再累加於此數字。</p></div>"""
assert old in s
s=s.replace(old,new)
page.write_text(s)

css=Path('app/globals.css')
c=css.read_text()
marker='/* ---------- 團隊工作狀況 ---------- */'
if marker not in c:
    c += '''\n\n/* ---------- 團隊工作狀況 ---------- */\n.project-dashboard-v2{display:grid;gap:10px;margin-bottom:14px}.project-status-row{display:grid;grid-template-columns:150px repeat(4,minmax(100px,1fr));gap:8px;align-items:stretch}.project-status-row>b{display:flex;align-items:center;padding:0 8px;font-size:13px}.project-status-row .stat{padding:10px 12px}.project-status-row .stat b{font-size:22px}.attention-filters{display:flex;gap:7px;align-items:center}.viewer-chip{font-size:11px;background:var(--idlebg);color:var(--muted);padding:6px 9px;border-radius:99px}.team-performance{display:grid;gap:8px}.performance-row{display:grid;grid-template-columns:minmax(105px,1.35fr) repeat(4,minmax(72px,1fr));gap:7px;align-items:stretch;border-top:1px solid var(--line);padding-top:8px}.performance-row:first-child{border-top:0;padding-top:0}.performance-person,.performance-metric{background:var(--idlebg);border-radius:8px;padding:9px}.performance-person{display:flex;flex-direction:column;justify-content:center}.performance-person>b{font-size:13px}.performance-person>small,.performance-metric>small{font-size:10px;color:var(--muted)}.performance-metric>b{display:block;font-size:15px;margin-top:2px}.danger-text{color:var(--stop)!important}.performance-note{font-size:10.5px;color:var(--muted);margin:10px 2px 0;line-height:1.5}.filters{grid-template-columns:minmax(220px,1fr) 190px 150px}.strategy-complete-toggle{display:flex;align-items:center;gap:7px;background:#ffffff16;border:1px solid #ffffff35;border-radius:9px;padding:8px 11px;font-size:12px}.strategy-complete-toggle.is-complete{background:#2f855a33;border-color:#8dd0a7}.strategy-complete-toggle input{accent-color:var(--ok)}\n@media(max-width:900px){.project-status-row{grid-template-columns:120px repeat(2,1fr)}.project-status-row>b{grid-row:span 2}.performance-row{grid-template-columns:1fr 1fr}.performance-person{grid-column:1/-1}.filters{grid-template-columns:1fr 1fr}.filters input{grid-column:1/-1}}\n@media(max-width:600px){.project-status-row{grid-template-columns:1fr 1fr}.project-status-row>b{grid-column:1/-1;grid-row:auto;padding:5px 2px}.performance-row{grid-template-columns:1fr 1fr}.attention-filters{width:100%;flex-wrap:wrap}.panel-head{align-items:flex-start;gap:8px;flex-direction:column}.filters{grid-template-columns:1fr}.filters input{grid-column:auto}}\n'''
    css.write_text(c)
