create table if not exists public.product_data_sheets (
  id bigint generated by default as identity primary key,
  project_id bigint not null unique references public.projects(id) on delete cascade,
  public_specs jsonb not null default '{}'::jsonb,
  internal_analysis jsonb not null default '{}'::jsonb,
  confirmation_status jsonb not null default '{}'::jsonb,
  completed boolean not null default false,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.product_data_sheets enable row level security;

drop policy if exists "product_data_sheets_select" on public.product_data_sheets;
create policy "product_data_sheets_select" on public.product_data_sheets for select to authenticated using (true);
drop policy if exists "product_data_sheets_insert" on public.product_data_sheets;
create policy "product_data_sheets_insert" on public.product_data_sheets for insert to authenticated with check (true);
drop policy if exists "product_data_sheets_update" on public.product_data_sheets;
create policy "product_data_sheets_update" on public.product_data_sheets for update to authenticated using (true) with check (true);
drop policy if exists "product_data_sheets_delete" on public.product_data_sheets;
create policy "product_data_sheets_delete" on public.product_data_sheets for delete to authenticated using (true);
